// netlify/functions/resend-code.js
// Looks up a purchase email in Gumroad, then emails the license key via Resend.

exports.handler = async function(event) {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: JSON.stringify({ success: false, error: 'Method not allowed' }) };
  }

  let email;
  try {
    var body = JSON.parse(event.body);
    email = (body.email || '').trim().toLowerCase();
  } catch(e) {
    return { statusCode: 400, body: JSON.stringify({ success: false, error: 'Invalid request' }) };
  }

  if (!email || !email.includes('@')) {
    return { statusCode: 400, body: JSON.stringify({ success: false, error: 'Please enter a valid email address.' }) };
  }

  const GUMROAD_TOKEN = process.env.GUMROAD_ACCESS_TOKEN;
  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  const PRODUCT_ID = 'FNqEFzXXRqr-uM1-cgu0iQ==';

  if (!GUMROAD_TOKEN || !RESEND_API_KEY) {
    return { statusCode: 500, body: JSON.stringify({ success: false, error: 'Service not configured.' }) };
  }

  // Look up the purchase in Gumroad by email
  try {
    var gumroadResp = await fetch(
      'https://api.gumroad.com/v2/sales?product_id=' + encodeURIComponent(PRODUCT_ID) + '&email=' + encodeURIComponent(email),
      {
        method: 'GET',
        headers: {
          'Authorization': 'Bearer ' + GUMROAD_TOKEN
        }
      }
    );

    var gumroadData = await gumroadResp.json();

    if (!gumroadData.success || !gumroadData.sales || gumroadData.sales.length === 0) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          success: false,
          error: 'We couldn\'t find a purchase for that email address. Please check the email you used at checkout, or contact smartscapeapp@gmail.com for help.'
        })
      };
    }

    // Get the most recent sale's license key
    var sale = gumroadData.sales[0];
    var licenseKey = sale.license_key;

    if (!licenseKey) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          success: false,
          error: 'We found your purchase but couldn\'t retrieve your license key. Please contact smartscapeapp@gmail.com for help.'
        })
      };
    }

    // Send the license key via Resend
    var emailResp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + RESEND_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'SmartScape Greenprint <noreply@mail.smartscape.co>',
        to: [email],
        subject: 'Your Greenprint Generator License Key',
        html: `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#f0f4eb;font-family:'Georgia',serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4eb;padding:32px 0;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;background:white;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
        <tr><td style="background:#1a3a0f;padding:28px 36px;">
          <p style="margin:0;font-size:11px;letter-spacing:0.12em;color:#c8e6b8;text-transform:uppercase;">SmartScape</p>
          <h1 style="margin:8px 0 4px;font-size:24px;color:white;font-weight:500;">Your License Key</h1>
          <p style="margin:0;font-size:14px;color:rgba(255,255,255,0.65);">Greenprint Generator — Beta Access</p>
        </td></tr>
        <tr><td style="padding:28px 36px;">
          <p style="font-size:15px;color:#333;line-height:1.6;margin:0 0 20px;">Here's your Greenprint Generator license key. Copy and paste it into the license key field at the gate.</p>
          <div style="background:#f0f7eb;border:2px solid #c8e6b8;border-radius:8px;padding:20px;text-align:center;margin:0 0 24px;">
            <p style="margin:0 0 8px;font-size:11px;color:#6b8f5e;letter-spacing:0.1em;text-transform:uppercase;">Your License Key</p>
            <p style="margin:0;font-size:20px;font-weight:600;color:#1a3a0f;letter-spacing:0.05em;font-family:monospace;">${licenseKey}</p>
          </div>
          <p style="font-size:13px;color:#666;line-height:1.6;margin:0 0 12px;">Visit <a href="https://greenprint-subscriber.netlify.app" style="color:#2d6a1f;">greenprint-subscriber.netlify.app</a> and enter this code to unlock your Greenprint Generator.</p>
          <p style="font-size:13px;color:#666;line-height:1.6;margin:0;">Questions? Email us at <a href="mailto:smartscapeapp@gmail.com" style="color:#2d6a1f;">smartscapeapp@gmail.com</a></p>
        </td></tr>
        <tr><td style="padding:20px 36px;background:#f0f7eb;">
          <p style="margin:0;font-size:11px;color:#5a7052;line-height:1.6;">Generated by <a href="https://greenprint-subscriber.netlify.app" style="color:#2d6a1f;">SmartScape Greenprint Generator</a> · Beta 2026</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
      })
    });

    var emailData = await emailResp.json();

    if (emailResp.ok) {
      return {
        statusCode: 200,
        body: JSON.stringify({ success: true })
      };
    } else {
      console.error('Resend error:', emailData);
      return {
        statusCode: 500,
        body: JSON.stringify({ success: false, error: 'Failed to send email. Please try again or contact smartscapeapp@gmail.com.' })
      };
    }

  } catch(err) {
    console.error('resend-code error:', err);
    return {
      statusCode: 500,
      body: JSON.stringify({ success: false, error: 'Something went wrong. Please contact smartscapeapp@gmail.com for help.' })
    };
  }
};
